SysTracker/Models/Link.cs
namespace SysTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Link")]
    public partial class Link
    {
        [Key]
        [Column(Order = 0)]
        [Required(ErrorMessage= "Server is required")]
        public Guid ServerID { get; set; }

        [Key]
        [Column(Order = 1)]
        [Required(ErrorMessage= "System is required")]
        public Guid SystemsID { get; set; }

        [Key]
        [Column(Order = 2)]
        [Required(ErrorMessage = "Server Type is required")]
        public Guid ServerTypeID { get; set; }

        //for navigation through EF
        public virtual Server Server { get; set; }
        public virtual Systems System { get; set; }
        public virtual ServerType ServerType { get; set; }
    }
}

SysTracker/Controllers/ServerTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SysTracker.Models;

namespace SysTracker.Controllers
{
    public class ServerTypesController : Controller
    {
        private Data_Models db = new Data_Models();

        // GET: ServerTypes
        public ActionResult Index()
        {
            return View(db.ServerTypes.OrderBy(m => m.Name).ToList());
        }

        // GET: ServerTypes/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerType serverType = db.ServerTypes.Find(id);
            if (serverType == null)
            {
                return HttpNotFound();
            }
            return View(serverType);
        }

        // GET: ServerTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServerTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServerTypeID,Name,Description")] ServerType serverType)
        {
            if (ModelState.IsValid)
            {
                serverType.ServerTypeID = Guid.NewGuid();
                db.ServerTypes.Add(serverType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serverType);
        }

        // GET: ServerTypes/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerType serverType = db.ServerTypes.Find(id);
            if (serverType == null)
            {
                return HttpNotFound();
            }
            return View(serverType);
        }

        // POST: ServerTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServerTypeID,Name,Description")] ServerType serverType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serverType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serverType);
        }

        // GET: ServerTypes/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerType serverType = db.ServerTypes.Find(id);
            if (serverType == null)
            {
                return HttpNotFound();
            }
            return View(serverType);
        }

        // POST: ServerTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ServerType serverType = db.ServerTypes.Find(id);
            //Check to make sure its not in use anywhere
            if (serverType.Links.Count > 0)
            {
                ModelState.AddModelError("", "You cannot delete this server type.  There are related systems and servers.  View them through the Details page and delete the link before deleting this.");
            }
            else
            {
                db.ServerTypes.Remove(serverType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serverType);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SysTracker/Controllers/ServersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SysTracker.Models;

namespace SysTracker.Controllers
{
    public class ServersController : Controller
    {
        private Data_Models db = new Data_Models();

        // GET: Servers
        public ActionResult Index()
        {
            return View(db.Servers.OrderBy(m => m.Name).ToList());
        }

        // GET: Servers/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Server server = db.Servers.Find(id);
            if (server == null)
            {
                return HttpNotFound();
            }
            return View(server);
        }

        // GET: Servers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServerID,Name,Description")] Server server)
        {
            if (ModelState.IsValid)
            {
                server.ServerID = Guid.NewGuid();
                db.Servers.Add(server);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(server);
        }

        // GET: Servers/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Server server = db.Servers.Find(id);
            if (server == null)
            {
                return HttpNotFound();
            }
            return View(server);
        }

        // POST: Servers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServerID,Name,Description")] Server server)
        {
            if (ModelState.IsValid)
            {
                db.Entry(server).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(server);
        }

        // GET: Servers/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Server server = db.Servers.Find(id);
            if (server == null)
            {
                return HttpNotFound();
            }
            return View(server);
        }

        // POST: Servers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Server server = db.Servers.Find(id);
            //Check to make sure it's not in use anywhere
            if (server.Links.Count > 0)
            {
                ModelState.AddModelError("", "You cannot delete this server.  There are related systems and server types.  View them through the Details page and delete the link before deleting this.");
            }
            else
            {
                db.Servers.Remove(server);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(server);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SysTracker/Controllers/SystemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SysTracker.Models;

namespace SysTracker.Controllers
{
    public class SystemsController : Controller
    {
        private Data_Models db = new Data_Models();

        // GET: Systems
        public ActionResult Index()
        {
            return View(db.Systems.OrderBy(m => m.Name).ToList());
        }

        // GET: Systems/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Systems systems = db.Systems.Find(id);
            if (systems == null)
            {
                return HttpNotFound();
            }
            return View(systems);
        }

        // GET: Systems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Systems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SystemsID,Name,Description")] Systems systems)
        {
            if (ModelState.IsValid)
            {
                systems.SystemsID = Guid.NewGuid();
                db.Systems.Add(systems);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(systems);
        }

        // GET: Systems/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Systems systems = db.Systems.Find(id);
            if (systems == null)
            {
                return HttpNotFound();
            }
            return View(systems);
        }

        // POST: Systems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SystemsID,Name,Description")] Systems systems)
        {
            if (ModelState.IsValid)
            {
                db.Entry(systems).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(systems);
        }

        // GET: Systems/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Systems systems = db.Systems.Find(id);
            if (systems == null)
            {
                return HttpNotFound();
            }
            return View(systems);
        }

        // POST: Systems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Systems systems = db.Systems.Find(id);
            //Check to make sure its not in use anywhere
            if (systems.Links.Count > 0)
            {
                ModelState.AddModelError("", "You cannot delete this system.  There are related servers and server types.  View them through the Details page and delete the link before deleting this.");
            }
            else
            {
                db.Systems.Remove(systems);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(systems);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SysTracker/Views/Links/Create.cshtml
@model SysTracker.Models.Link

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Link</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Server, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ServerID, new SelectList(ViewBag.Servers, "ServerID", "Name"), "Select Server")
                <div class="text-danger">
                    @Html.ValidationMessageFor(m => m.ServerID)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.System, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SystemsID, new SelectList(ViewBag.Systems, "SystemsID", "Name"), "Select System")
                <div class="text-danger">
                    @Html.ValidationMessageFor(m => m.SystemsID)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ServerType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ServerTypeID, new SelectList(ViewBag.ServerTypes, "ServerTypeID", "Name"), "Select System Type")
                <div class="text-danger">
                    @Html.ValidationMessageFor(m => m.ServerTypeID)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SysTracker/Views/Links/Delete.cshtml
@model SysTracker.Models.Link

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Link?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="form-group">
        @Html.LabelFor(m => m.Server, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DisplayFor(m => m.Server.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.System, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DisplayFor(m => m.System.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ServerType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DisplayFor(m => m.ServerType.Name)
        </div>
    </div>
</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SysTracker/Views/Links/Edit.cshtml
@model SysTracker.Models.Link

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Link</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Server, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ServerID, new SelectList(ViewBag.Servers, "ServerID", "Name"))
            <div class="text-danger">
                @Html.ValidationMessageFor(m => m.ServerID)
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.System, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.SystemsID, new SelectList(ViewBag.Systems, "SystemsID", "Name"))
            <div class="text-danger">
                @Html.ValidationMessageFor(m => m.SystemsID)
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ServerType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ServerTypeID, new SelectList(ViewBag.ServerTypes, "ServerTypeID", "Name"))
            <div class="text-danger">
                @Html.ValidationMessageFor(model => model.ServerTypeID)
            </div>
        </div>
        <!--for storing the old IDs so we can delete and recreate in the controller-->
        @Html.Hidden("oldServerID", Model.ServerID)
        @Html.Hidden("oldSystemsID", Model.SystemsID)
        @Html.Hidden("oldServerTypeID", Model.ServerTypeID)
        @Html.HiddenFor(m => m.ServerID)
        @Html.HiddenFor(m => m.SystemsID)
        @Html.HiddenFor(m => m.ServerTypeID)
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SysTracker/Views/Links/Index.cshtml
@model IEnumerable<SysTracker.Models.Link>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Server)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.System)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServerType)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Server.Name, "Details", "Servers", new { id = item.ServerID }, null)
        </td>
        <td>
            @Html.ActionLink(item.System.Name, "Details", "Systems", new { id = item.SystemsID }, null)
        </td>
        <td>
            @Html.ActionLink(item.ServerType.Name, "Details", "ServerTypes", new { id = item.ServerTypeID }, null)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { serverID=item.ServerID, systemID = item.SystemsID, serverTypeID = item.ServerTypeID }) |
            @Html.ActionLink("Delete", "Delete", new { serverID = item.ServerID, systemID = item.SystemsID, serverTypeID = item.ServerTypeID })
        </td>
    </tr>
}

</table>